<a href="https://colab.research.google.com/github/LohanVaddepally/Consulting-Workflow-Automation/blob/main/Consulting_workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import sqlite3

In [4]:
data = {
   "store": ["store A", "store B", "store C", "store D"],
   "sales": [50000, 20000, 70000, 18000],
   "inventory": [10000, 12000, 15000, 9000],
   "returns": [3000, 4000, 1000, 5000]
}

df = pd.DataFrame(data)

df

     store  sales  inventory  returns
0  store A  50000      10000     3000
1  store B  20000      12000     4000
2  store C  70000      15000     1000
3  store D  18000       9000     5000

In [5]:
df["return_rate"] = (
    df["returns"] / df["sales"]
)
df

     store  sales  inventory  returns  return_rate
0  store A  50000      10000     3000     0.060000
1  store B  20000      12000     4000     0.200000
2  store C  70000      15000     1000     0.014286
3  store D  18000       9000     5000     0.277778

In [11]:
def generate_recomendation(row):

    if row["sales"] < 25000:
       return "increase marketing efforts"

    elif row["return_rate"] > 0.15:
       return "investigate product quality"

    else:
        return "maintain current startegy"

In [12]:
df["recommendation"] = df.apply(
    generate_recomendation,
    axis=1
)

df

     store  sales  inventory  returns  return_rate              recommendation
0  store A  50000      10000     3000     0.060000   maintain current startegy
1  store B  20000      12000     4000     0.200000  increase marketing efforts
2  store C  70000      15000     1000     0.014286   maintain current startegy
3  store D  18000       9000     5000     0.277778  increase marketing efforts

In [13]:
conn = sqlite3.connect(
    "consulting_analysis.db"
)

df.to_sql(
    "store_analysis",
    conn,
    if_exists="replace",
    index=False
)

print("saved to SQL database")

saved to SQL database

In [14]:
df.to_excel(
    "recommendation.xlsx",
    index=False
)

print("excel report created")

excel report created

In [15]:
print("==============================")
print("Consulting Workflow Automation")
print("==============================")

print("\nStores analyzed:", len(df))
print("\nRecommendations:")
for _, row in df.iterrows():
    print(
        f"{row['store']} -> {row['recommendation']}"
    )

==============================
Consulting Workflow Automation
==============================

Stores analyzed: 4

Recommendations:
store A -> maintain current startegy
store B -> increase marketing efforts
store C -> maintain current startegy
store D -> increase marketing efforts